inherit_from: "configs/rgbd/replicav2/base_config.yaml"
Dataset:
  dataset_path: "/media/saimouli/RPNG_FLASH_4/datasets/Replica2/vmap/room_0_small/imap/00"
  single_thread: False
Results:
  use_gui: False
Training:
  kf_interval: 4 #1
  mapping_itr_num: 150 #15
  gaussian_update_every: 150 #100
  gaussian_update_offset: 50
  gaussian_reset: 2001
  size_threshold: 20 #5
  use_gt_pose: False 
language:
  labels_from_file: False # if True, will load labels from a file (can be low res or high res langsplat labels) instead of running online language model
  language_train: True # if True, will train for the language
  single_stage_ae: False # if True, will use cross-data ae (pretrained on cross-data of replica), if false will use a 2-stage ae
  #auto_ckpt_path: "/home/saimouli/Desktop/Bosch/autoencoder_omni_cross/run1_code15_omni/lightning_logs/version_0/checkpoints/epoch=59-step=2520.ckpt" #uncomment this to use the pretrained model
  hr_model: True
  lang_code_size: 15
  online_ckpt_path: "/media/saimouli/Data6T/Replica/omni_data_result/online_15_room0.pth"